name: Check Formatting

on:
  workflow_run:
    workflows: "C++ Formatting"
    types:
      - completed

jobs:
  check_clang_format:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install clang-format
        run: sudo apt-get install clang-format

      - name: Check C++ formatting
        run: |
          # Get list of C++ files
          cpp_files=$(find src/main_ws/src -type f -name "*.cpp" -o -name "*.hpp" -o -name "*.h")

          # Check formatting for each file
          for file in $cpp_files; do
            if ! clang-format -style=file -output-replacements-xml "$file" | grep -q "<replacement "; then
              echo "File $file is correctly formatted."
            else
              echo "File $file is incorrectly formatted."
              exit 1
            fi
          done
