name: C++ Formatting

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: clang-format Code Formatter
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Copy formatting
        run: cp ./.clang-format ./.github/actions/cppformat

      - name: Clang Code Formatter
        uses: ./.github/actions/cppformat
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  check_format:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install clang-format
        run: |
          sudo apt-get install -y lsb-release \
            wget \
            software-properties-common \
            gnupg \
            && sudo wget https://apt.llvm.org/llvm.sh \
            && sudo chmod +x llvm.sh \
            && sudo ./llvm.sh 16 \
            && sudo apt-get install -y clang-format-16 \
            && sudo ln -s $(which clang-format-16) /usr/local/bin/clang-format


      - name: Check C++ formatting
        run: |
          # Get list of C++ files
          cpp_files=$(find src/main_ws/src -type f -name "*.cpp" -o -name "*.hpp" -o -name "*.h")

          # Check formatting for each file
          for file in $cpp_files; do
            if ! clang-format -style=file -output-replacements-xml "$file" | grep -q "<replacement "; then
              echo "File $file is correctly formatted."
            else
              echo "File $file is incorrectly formatted."
              exit 1
            fi
          done
