name: Verify C++ Formatting

on:
  pull_request:
    branches:
      - main

jobs:
  verify_formatting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Clang-Format
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format

      - name: Verify C++ Formatting
        run: |
          # List all C++ files in the repository
          cpp_files=$(find . -type f -name "*.cpp" -o -name "*.hpp" -o -name "*.h" -o -name "*.cc" -o -name "*.cxx")

          # Check if any files need formatting
          for file in $cpp_files; do
            formatted=$(clang-format -style=file "$file" | cmp -s "$file" -)
            if [ $? -ne 0 ]; then
              echo "File $file does not match the required formatting. Please run clang-format."
              exit 1
            fi
          done
