name: Verify C++ formatting

on:
  pull_request:
    branches: [main]

jobs:
  clang-format-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DoozyX/clang-format-lint@v0.12
        with:
          source: '.'  # Check all C++ files in the repository
          clangFormatFile: '.clang-format'  # Use the custom .clang-format file
          failOnFormatChanges: true  # Fail immediately if any formatting issues found
