name: Check C++ Formatting
on:
  pull_request:
    branches:
      - main

jobs:
  check_format:
    name: Check C++ Formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install clang-format
        run: sudo apt-get install clang-format

      - name: Check C++ formatting
        run: |
          # Get list of C++ files
          cpp_files=$(find . -type f -name "*.cpp" -o -name "*.h")

          # Check formatting for each file
          for file in $cpp_files; do
            if ! clang-format -style=file -output-replacements-xml "$file" | grep -q "<replacement "; then
              echo "File $file is correctly formatted."
            else
              echo "File $file is incorrectly formatted."
              exit 1
            fi
          done
