name: Formatter

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  clang-format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: AutoModality/action-ros-clang-format@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
