name: clang-format Code Formatter

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: clang-format Code Formatter
    runs-on: ubuntu-latest
    steps:
      - name: Clang Code Formatter
        uses: .github/actions/cppformat
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
