name: clang-format Code Formatter

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: clang-format Code Formatter
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Copy formatting
        run: cp ./.clang-format ./.github/actions/cppformat

      - name: Clang Code Formatter
        # with:
        #   ref: ${{ github.head_ref }}
        uses: ./.github/actions/cppformat
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
